Repository tektoncd/catlin, pull requests merged in 2023-11, with the labels that each got.

#13 Fix linting issues to unblock CI build tests
  pkg/cmd/validate/validate_test.go
  pkg/validator/helper.go
Labels: size/XS, approved, lgtm

#12 Making catlin useable as a pre-commit hook
  .pre-commit-hooks.yaml
  README.md
Labels: size/M, approved, lgtm, ok-to-test

#14 Fail lint check if linter is not installed.
  pkg/linter/script.go
Labels: size/XS, approved, lgtm, ok-to-test
